#!/bin/bash

#Load config
. ./git-shell-commands/config

if [ $# -ne 1 ]
then
	echo "Usage:"
	echo "create-repo [name]"
	echo ""
	echo "Creates a new git repository."
	exit
fi

#Check that input does not contain /
if [ `echo $1 | grep -c /` -ne 0 ]
then
	echo "ERROR: You cannot create a git repository containing the / character"
	exit
fi

#Create repo
if [ ! -e "$GITROOT/$1" ]
then
	echo -n "Creating repository folder [$1]..."
	mkdir "$GITROOT/$1"
	echo "Done"
	echo "Creating bare git repository"
	git init --bare "$GITROOT/$1"
	echo "Repository successfully created"
else
	echo "ERROR: Repository already exists: $1"
fi

