#!/bin/bash

# Load config
. ./git-shell-commands/config

if [ $# -ne 1 ]
then
	exit
fi

# Check that input does not contain /
if [ `echo $1 | grep -c /` -ne 0 ]
then
        exit
fi

# List branches
cd "$GITROOT/$1" > /dev/null 2>&1
if [ $? -ne 0 ]
then
	exit
fi

git branch | cut -d' ' -f2- | sed 's/^[[:space:]]*//'
