#!/bin/bash

# Load config
. ./git-shell-commands/config

if [ $# -ne 3 ]
then
        exit
fi

# Check that input does not contain /
if [ `echo $1 | grep -c /` -ne 0 ]
then
        exit
fi

# Show file
cd "$GITROOT/$1" > /dev/null 2>&1
if [ $? -ne 0 ]
then
        exit
fi

OUTPUT=`git show $2:$3 2>/dev/null`
if [ $? -ne 0 ]
then
        exit
fi

echo "$OUTPUT"
