#!/bin/bash

# Load config
. ./git-shell-commands/config

if [ $# -ne 2 ]
then
        exit
fi

# Check that input does not contain /
if [ `echo $1 | grep -c /` -ne 0 ]
then
        exit
fi

# Get log
cd "$GITROOT/$1" > /dev/null 2>&1
if [ $? -ne 0 ]
then
        exit
fi

re='^-+'
if [[ $2 =~ $re ]]
then
	exit
fi

git log -1 $2
