#!/bin/bash

# Load config
. ./git-shell-commands/config

if [ $# -ne 1 ]
then
        echo "Usage:"
        echo "show-log [repository]"
        echo ""
        echo "Display git repository log."
        exit
fi

# Check that input does not contain /
if [ `echo $1 | grep -c /` -ne 0 ]
then
        echo "ERROR: you cannot specify a git repository containing the / character"
        exit
fi

# Get log
cd "$GITROOT/$1" > /dev/null 2>&1
if [ $? -ne 0 ]
then
        echo "ERROR: Cannot access repository with name $1"
        exit
fi

echo "Log for $1:"
echo ""
git log
